# Generated by Django 4.2.2 on 2024-11-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "cname",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("population", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "country",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "disease_code",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("pathogen", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=140, null=True),
                ),
            ],
            options={
                "db_table": "disease",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Diseasetype",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=140, null=True),
                ),
            ],
            options={
                "db_table": "diseasetype",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "email",
                    models.CharField(max_length=60, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(blank=True, max_length=30, null=True)),
                ("surname", models.CharField(blank=True, max_length=40, null=True)),
                ("salary", models.IntegerField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Discover",
            fields=[
                (
                    "cname",
                    models.OneToOneField(
                        db_column="cname",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="crud.country",
                    ),
                ),
                ("first_enc_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "discover",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "email",
                    models.OneToOneField(
                        db_column="email",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="crud.users",
                    ),
                ),
                ("degree", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "doctor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Patientdisease",
            fields=[
                (
                    "email",
                    models.OneToOneField(
                        db_column="email",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="crud.users",
                    ),
                ),
            ],
            options={
                "db_table": "patientdisease",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "email",
                    models.OneToOneField(
                        db_column="email",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="crud.users",
                    ),
                ),
            ],
            options={
                "db_table": "patients",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Publicservant",
            fields=[
                (
                    "email",
                    models.OneToOneField(
                        db_column="email",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="crud.users",
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "publicservant",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Specialize",
            fields=[
                (
                    "disease",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="crud.diseasetype",
                    ),
                ),
            ],
            options={
                "db_table": "specialize",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "email",
                    models.OneToOneField(
                        db_column="email",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="crud.publicservant",
                    ),
                ),
                ("total_deaths", models.IntegerField(blank=True, null=True)),
                ("total_patients", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "record",
                "managed": False,
            },
        ),
    ]
